export const logos = [
  { src: "logos/react.svg", alt: "React", popover: "React", duration: 0.2 },
  {
    src: "logos/nextjs.svg",
    alt: "Next.js",
    popover: "Next.js",
    duration: 0.25,
  },
  {
    src: "logos/node-js.svg",
    alt: "Node.js",
    popover: "Node.js",
    duration: 0.3,
  },
  {
    src: "logos/express.svg",
    alt: "ExpressJS",
    popover: "ExpressJS",
    duration: 0.35,
  },
  {
    src: "logos/js.svg",
    alt: "JavaScript",
    popover: "JavaScript",
    duration: 0.4,
  },
  { src: "logos/html5.svg", alt: "HTML5", popover: "HTML5", duration: 0.45 },
  { src: "logos/css.svg", alt: "CSS", popover: "CSS", duration: 0.5 },
  { src: "logos/sass.svg", alt: "Sass", popover: "Sass", duration: 0.55 },
  {
    src: "logos/tailwind.svg",
    alt: "Tailwind CSS",
    popover: "Tailwind CSS",
    className: "w-32 flex justify-center",
    duration: 0.6,
  },
  {
    src: "logos/bootstrap.svg",
    alt: "Bootstrap",
    popover: "Bootstrap",
    duration: 0.65,
  },
  {
    src: "logos/database.svg",
    alt: "SQL",
    popover: "SQL",
    duration: 0.7,
  },
  { src: "logos/docker.svg", alt: "Docker", popover: "Docker", duration: 0.75 },
  {
    src: "logos/postgresql.svg",
    alt: "PostgreSQL",
    popover: "PostgreSQL",
    duration: 0.8,
  },
  { src: "logos/linux.svg", alt: "Linux", popover: "Linux", duration: 0.85 },
  { src: "logos/git-alt.svg", alt: "Git", popover: "Git", duration: 0.9 },
  { src: "logos/cpanel.svg", alt: "cPanel", popover: "cPanel", duration: 1 },
];
